### ISSUE TITLE
does not export to jpg?

### ISSUE THREAD

**Issue by Hoogkamer** [upsetjs/cytoscape.js-bubblesets#11]
Hi, I am trying to export to jpg (https://js.cytoscape.org/#cy.jpg) but then in the export the bubbleset is not visible. How can I export so I can share the graph including the bubblesets?

Thanks!

**Comment by sgratzl** [comment]
that is currently not possible. this plugin is based on https://github.com/sgratzl/cytoscape.js-layers which allows one to use multiple layers (canvas, svg, html) within the same cytoscape view. However, AFAIK there is no way to customize cytoscape to also consider exporting those custom layers when exporting to a JPG.

**Comment by Hoogkamer** [comment]
Ok, clear. It is a nice visualisation, thanks for making this.

**Comment by dpdoughe** [comment]
Is the only work-around a screenshot then? Could at the SVG be exported more directly in some way?

**Comment by sgratzl** [comment]
you can grab the underlying canvas and convert that to images and merge them manually. As I said what would be needed is that cytoscape.js allows plugins to extend and customize the `.png` or `.jpg` function. Based on that, plugins like cytoscape.js-layers can hook into it and try to render its content, too. 

It won't work in every case (e.g. HTML based layers) but it would at least give it a chance

**Comment by sgratzl** [comment]
https://github.com/sgratzl/cytoscape.js-layers added a basic support for canvas layers which the bubblesets layer is

**Comment by dpdoughe** [comment]
This is great. So it sounds like export to jpg may be supported out-of-the-box now?
