### ISSUE TITLE
Dead example link

### ISSUE THREAD

**Issue by maxkfranz** [upsetjs/cytoscape.js-bubblesets#12]
@sgratzl 

When I click on the codepen badge, it says 404: https://codepen.io/sgratzl/pen/TODO

There's a TODO in the link.  Maybe the demo exists but it's just not in the readme?

**To Reproduce**

1. Click https://codepen.io/sgratzl/pen/TODO

**Expected behavior**

I expect it to open a demo of the pictured graph in the readme.

**Screenshots**

N/A

**Context**

- Version: N/A
- Browser: N/A

**Additional context**

Thanks!

**Comment by sgratzl** [comment]
I never had the time to write one, here you go https://codepen.io/sgratzl/pen/RwQdBLY

see also https://github.com/upsetjs/cytoscape.js-bubblesets/tree/main/samples

**Comment by maxkfranz** [comment]
The demo looks great.  Could you update the link in the readme?  It's still dead for me

Maybe the codepen badge could also be at the top of the readme with the other badges?  I think a lot of people would want to access the demo, and the top of the readme is the most seen place
