### ISSUE TITLE
Could not resolve "cytoscape-layers"

### ISSUE THREAD

**Issue by jthrilly** [upsetjs/cytoscape.js-bubblesets#13]
I updated from 2.x to latest 3.x using `yarn add -D cytoscape-bubblesets@latest`, and am now receiving the following error:

```
✘ [ERROR] Could not resolve "cytoscape-layers"

    node_modules/cytoscape-bubblesets/build/index.js:12:30:
      12 │ var cytoscapeLayers = require('cytoscape-layers');
```

I see that `cytoscape-layers` is in the package, so I suspect this is an issue with the way yarn pulled in the dependencies. 

I am running this in Electron (17.x) which could also be playing a role.

**Comment by sgratzl** [comment]
cytoscape-layers is declared as a peer dependency similar to a cytoscape.js itself. you have to install it next to it

see https://github.com/upsetjs/cytoscape.js-bubblesets/blob/5726afd9a2f08e2b3ebbd2ac240bf4b26b61017f/package.json#L32

**Comment by jthrilly** [comment]
That's what I ended up doing. Perhaps a note in the readme? Your install example uses npm (which installs peer dependencies, I believe?) and includes cytoscape but not cytoscape-layers.

`yarn add cytoscape cytoscape-layers cytoscape-bubblesets`
