### ISSUE TITLE
How to add label to bubbleset and/or to a legend?

### ISSUE THREAD

**Issue by dpdoughe** [upsetjs/cytoscape.js-bubblesets#15]
Are there any examples of how to put a text label on the bubblesets?  Related question, how about having a legend with the color of the bubbleset and the text label appearing?  If there are examples that show this already that would be great. Thanks in advance!

**Comment by sgratzl** [comment]
this plugin doesn't support creating a legend, you could try use https://github.com/sgratzl/cytoscape.js-layers to manually add a legend as an overlay / annotaiton

**Comment by mikekucera** [comment]
I've done this by putting all the nodes that I want in the bubbleset into a compound node as well, and then setting the label on the compound node. With the right style options you can hide the compound node.
