### ISSUE TITLE
wish  bubblesets could listen to click event

### ISSUE THREAD

**Issue by Shenchuanhuan** [upsetjs/cytoscape.js-bubblesets#2]
It would be great if group(nodes in path as a group) click will be listened

**User story**

I grouped nodes with the plugin. and anywhere clicked in the group will be treated as group click. but  now click event only be node or cytoscape instance. could group click be responsed ?

https://codepen.io/KonnieShen/pen/abdgwbd?editors=1000

**Comment by sgratzl** [comment]
have you taken a look at the bubblecluster example, especially: 
https://github.com/upsetjs/cytoscape.js-bubblesets/blob/1986d85620d5eb540227fdd68e79012e23ba97f4/samples/bubbleclusters.html#L95

**Comment by Shenchuanhuan** [comment]
> have you taken a look at the bubblecluster example, especially:
> https://github.com/upsetjs/cytoscape.js-bubblesets/blob/1986d85620d5eb540227fdd68e79012e23ba97f4/samples/bubbleclusters.html#L95

yes. i tried the example. but it is not what i need. how could i know when i click the blank of group(not the node)

**Comment by sgratzl** [comment]
when you add a path you also have access to its underlying SVG path via its return value: (`.node`) so you can add any event listener you like

**Comment by Shenchuanhuan** [comment]
> when you add a path you also have access to its underlying SVG path via its return value: (`.node`) so you can add any event listener you like

thx!!  it works. it helps me a lot. i update my demo.
https://codepen.io/KonnieShen/pen/abdgwbd?editors=1000
