### ISSUE TITLE
 Can not register `bubbleSets` for `core` since `bubbleSets` already exists in the prototype and can not be overridden

### ISSUE THREAD

**Issue by Shenchuanhuan** [upsetjs/cytoscape.js-bubblesets#3]
hi there!

I used extension in  pageA.

I registered extension with:
```
   cytoscape.use(plugin)
```

when pageA loaded first time, it show what expected. But when leave pageA and back again. pageA crashed.
and it will throw this error when the component is hot replaced(by wepack-dev-server).

```
 Can not register `bubbleSets` for `core` since `bubbleSets` already exists in the prototype and can not be overridden
```

**Comment by sgratzl** [comment]
seems like you should ask the cytoscape guys directly since this plugin cannot influence the registration process
