### ISSUE TITLE
compound nodes don't update their children's bubblesets when moved

### ISSUE THREAD

**Issue by setr** [upsetjs/cytoscape.js-bubblesets#6]
If a node is in a bubbleset, it updates on position events

If a compound node itself is in a bubbleset, it updates on position events

If a compound node's child is in a bubbleset, it **does not** update on position events where the compound node is being moved. If you move the node itself, it updates the bubbleset correctly.

**Current Behavior**
![bubbleset_compound_bug](https://user-images.githubusercontent.com/7907343/109696783-46c05580-7b42-11eb-9826-f9840d32b4b6.gif)

**Expected Behavior**
![bubbleset_compound_bug_corrected](https://user-images.githubusercontent.com/7907343/109697078-a3bc0b80-7b42-11eb-8aa6-2fd2e9f22911.gif)

Trying to force the update with `bubbleSets().update()` does nothing
```
cy.on('position', 'node', function(evt){
  const tgt = event.target;
  const bb = cy.bubbleSets();
  if (tgt.isParent()){ 
     bb.update() 
  }
});
```
I believe the issue is with how nextPotentialBB is being calculated, but I haven't dug in further.

My current workaround (used to produce the expected behavior gif) is to **delete and recreate the path** on every compound node position update.

**Comment by sgratzl** [comment]
the plugin is listening to the `position` event of its nodes. However, cytoscape doesn't seem to trigger them when the component around it is moved. 

But, your suggested workaround works for me: 

https://codepen.io/sgratzl/pen/gOLzVgz?editors=0010

**Comment by sgratzl** [comment]
closing -> stale
