### ISSUE TITLE
Not working in Angular

### ISSUE THREAD

**Issue by crlsmsq** [upsetjs/cytoscape.js-bubblesets#7]
I tried to use this library in my Angular 10 application, and I got this error when importing it.

```
import cytoscape from 'cytoscape';
import BubbleSets from 'cytoscape-bubblesets';
cytoscape.use(BubbleSets); // BubbleSets have the red line
```

```
Argument of type '(cytoscape: (type: "collection" | "layout" | "core", name: string, extension: any) => void) => void' is not assignable to parameter of type 'Ext'.
  Types of parameters 'cytoscape' and 'cytoscape' are incompatible.
    Types of parameters 'options' and 'type' are incompatible.
      Type 'string' is not assignable to type 'CytoscapeOptions'.
        Type '"collection"' has no properties in common with type 'CytoscapeOptions'.
```

These was in my package.json file

```
    "@types/cytoscape": "^3.14.7",
    "cytoscape": "^3.17.0",
    "cytoscape-bubblesets": "^3.0.0",
    "cytoscape-layers": "^2.1.0",

```

**To Reproduce**

1. Have an Angular Project
2. npm install cytoscape cytoscape-bubblesets
3. Import the libraries in the component

**Context**

- Version: cytoscape-bubbleset 3.0.0
- Browser: Chrome

**Additional context**

**Comment by sgratzl** [comment]
the typings of cytosccape for plugins aren't the best, According to the docs the plugin this plugin assumes the right structure. Seems like you have to cast to convince the compiler

**Comment by crlsmsq** [comment]
okay ill find a way to cast it then :D thank you!
