### ISSUE TITLE
Does cytoscape.js-bubblesets allow intersections a.k.a. overlapping sets?

### ISSUE THREAD

**Issue by dpdoughe** [upsetjs/cytoscape.js-bubblesets#8]
Cytoscape.js has compound nodes, but these only permit hierarchical/nested relationships. Do bubblesets permit non-nested intersections between 2 groups of nodes?

**Comment by sgratzl** [comment]
bubble sets are independent on the graph structure. You define them via a set of nodes that should form one cluster. This cluster is then rendering with a dynamically computed bubble on top of the existing graph layout. So, if I understand your question correctly, yes you can do what you are looking for

**Comment by dpdoughe** [comment]
Thanks! So the limitation (so to say) is that the set information is not used by the layout algorithms. If nodes belong to the intersection between 2 sets then the layout won't try harder to place the nodes of those sets closer together. Is that correct?

**Comment by sgratzl** [comment]
the plugin in not a layout algorithm, so it won't affect the layout. This plugin allows you to connect nodes together and this plugin figures out a way to connect them via a bubbleset which is then rendered.
