### ISSUE TITLE
npm package nullish coalescing operators

### ISSUE THREAD

**Issue by grinspins** [upsetjs/cytoscape.js-bubblesets#9]
The built index.js published on npm contains nullish coalescing operators. Since Webpack 4 does not support them, it is necessary to run the package through Babel again. Would it be possible to lower the build target from ES2020 to maybe ES2018, for out of the box compatibility with Webpack 4?

**Comment by dpdoughe** [comment]
Agreed this would be nice.

**Comment by sgratzl** [comment]
can you give the latest v3.1.0 version a try

**Comment by grinspins** [comment]
Thank you @sgratzl for working on this! Version 3.1.0 worked for me.
